version: '3.1'

services:
  Db:
    image: mysql:5.7
    volumes:
      - .\mysql\init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: Db
      MYSQL_ROOT_USER: root
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root