version: '3.1'

services:
  db:
    image: mysql:5.7
    # volumes:
    #   - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    # command: --init-file /docker-entrypoint-initdb.d/init.sql
    restart: always
    ports:
      - "3312:3306"
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_USER: samir
      MYSQL_USER: samir
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret